### ISSUE TITLE
There are no roles

### ISSUE THREAD

**Issue by levalencia** [Azure-Samples/active-directory-dotnet-webapp-groupclaims#29]
The last commit does not return true when using User.IsInRole, if possible Id like to have a chat with you to discuss this as I am kind of stuck.
http://stackoverflow.com/questions/30574787/authorization-in-cloud-applications-using-ad-groups-issue-with-new-group

**Comment by klausenlie** [comment]
Hi.
I am kind of stuck as to what I should do with the same issue, that you got. But basicly I`m just using this sample app to build a different business logic on, but it would be great to see this one working as expected. 
When I click on "About", shouldn`t I see my roles?
Because when I click on "Tasks" I get an error that I don`t have enough permissions to view the page.

**Comment by jmprieur** [comment]
Resolved by commit b9e4f80bbe1cb7f024542af4d40568d42d62ad6e, along with #39
