### ISSUE TITLE
Fully Qualified Name Less Than 260 Characters Microsoft.Azure.ActiveDirectory.GraphClient 2.0.0

### ISSUE THREAD

**Issue by largeDachshund** [Azure-Samples/active-directory-dotnet-webapp-groupclaims#33]
Can't compile the solution.  When you try to restore the packages, this one has an issue.

I'm on Visual Studio 2015 Community Edition.

**Comment by jmprieur** [comment]
This is due to the .NET Framework/Windows limitation in the length of paths.

Because the name of the project is pretty long already, and the name of some NuGet packages is a fully qualified name, you need to clone the repo into a folder which is close to the root of your hard disk (probably not under \Users\xxxxxxxx\Source\Repos\something)
